// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChMtVSpDZmQNHL-SOdLM7h5ImLMPfxDgE',
    appId: '1:745350814117:web:b4f06e06dc3240c3eaf04c',
    messagingSenderId: '745350814117',
    projectId: 'easydiet-568f1',
    authDomain: 'easydiet-568f1.firebaseapp.com',
    storageBucket: 'easydiet-568f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1msTTCI5bO7w6ju-fVtVJM73gxVwjlF4',
    appId: '1:745350814117:android:fd6bb192a1d0799aeaf04c',
    messagingSenderId: '745350814117',
    projectId: 'easydiet-568f1',
    storageBucket: 'easydiet-568f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiygS7oJLlz_muvChmaYggdMePsRc-g-c',
    appId: '1:745350814117:ios:9d269592b67ff5c6eaf04c',
    messagingSenderId: '745350814117',
    projectId: 'easydiet-568f1',
    storageBucket: 'easydiet-568f1.firebasestorage.app',
    iosBundleId: 'com.example.easydiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiygS7oJLlz_muvChmaYggdMePsRc-g-c',
    appId: '1:745350814117:ios:9d269592b67ff5c6eaf04c',
    messagingSenderId: '745350814117',
    projectId: 'easydiet-568f1',
    storageBucket: 'easydiet-568f1.firebasestorage.app',
    iosBundleId: 'com.example.easydiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChMtVSpDZmQNHL-SOdLM7h5ImLMPfxDgE',
    appId: '1:745350814117:web:f07f5332142ac47deaf04c',
    messagingSenderId: '745350814117',
    projectId: 'easydiet-568f1',
    authDomain: 'easydiet-568f1.firebaseapp.com',
    storageBucket: 'easydiet-568f1.firebasestorage.app',
  );
}
